#!/usr/bin/env python


from sys import argv, stderr, exit
from time import sleep

from selenium.webdriver import Chrome
from selenium.webdriver.common.keys import Keys


# number of seconds to wait for feed to load
FEED_LOAD_TIME = 3

# CSS selector for the <span> whose aria-label contains the duration of the video
TIME_SELECTOR = '#items ytd-thumbnail-overlay-time-status-renderer span'


def scroll_till_end(driver):
    """Scroll to the end of a progessively loading feed."""

    while True:
        hi = driver.execute_script("return document.documentElement.scrollHeight")
        driver.find_element_by_tag_name('body').send_keys(Keys.END)
        sleep(FEED_LOAD_TIME)
        hf = driver.execute_script("return document.documentElement.scrollHeight")

        if hi == hf:
            break


def calc_total_time(times):
    """Calculate the sum of all times passed in."""

    hours = 0
    minutes = 0
    seconds = 0

    for (i, t) in enumerate(times, start=1):
        t_units = t.split(', ')
        ntu = len(t_units)

        try:
            if ntu >= 1:
                seconds += int(t_units[-1][:2])
            if ntu >= 2:
                minutes += int(t_units[-2][:2])
            if ntu == 3:
                hours += int(t_units[-3][:2])
        except ValueError:
            continue

    minutes += seconds // 60
    seconds %= 60

    hours += minutes // 60
    minutes %= 60

    return (hours, minutes, seconds)


def main(url):
    driver = Chrome()
    driver.get(url)

    scroll_till_end(driver)

    times = []
    for time_span in driver.find_elements_by_css_selector(TIME_SELECTOR):
        times.append(time_span.get_attribute('aria-label'))

    driver.quit()

    print(("{} hour(s), {} minute(s) and {} second(s) from {} video(s).").format(*calc_total_time(times), len(times)))


if __name__ == '__main__':
    if len(argv) != 2:
        print("Usage: {} URL".format(argv[0]), file=stderr)
        exit(1)

    main(argv[1])